service: stack-${self:custom.conf.userenv}-${self:custom.conf.name}
frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  conf:
    userenv: ${opt:userenv, 'unknown'}
    deploymentbucket: tco-s3
    name: ${opt:name,'noname'}

provider:
  name: aws
  region: eu-west-3
  deploymentBucket: ${self:custom.conf.deploymentbucket}
  stackTags:
    'testtag:user': tco

functions:
  LambdaTest1:
    name: lambda-${self:custom.conf.userenv}-helloW-1
    handler: lambda-test1/helloworld.handler
    runtime: python3.6

  LambdaTest2:
    name: lambda-${self:custom.conf.userenv}-helloW-2
    handler: lambda-test2/helloworld.handler
    runtime: python3.6