service: stack-${self:custom.conf.variant}-${self:custom.conf.name}-${self:custom.conf.object}
frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  conf:
    userenv: ${opt:userenv, 'unknown'}
    profile: ${opt:profile,'unknown'}
    variant: ${opt:variant,'stable'}
    deploymentbucket: tco-s3
    name: lambda-test
    object: ${opt:object,'--object_missing'}

provider:
  name: aws
  region: eu-west-3
  deploymentBucket: ${self:custom.conf.deploymentbucket}
  stage: ${self:custom.conf.variant}
  stackTags:
    'testtag:user': tco

functions:
  LambdaTest1:
    name: lambda-${self:custom.conf.variant}-helloW-1
    handler: lambda-test1/helloworld.handler
    runtime: python3.6

  LambdaTest2:
    name: lambda-${self:custom.conf.variant}-helloW-2
    handler: lambda-test2/helloworld.handler
    runtime: python3.6