service: stack-lab-lambda-tco
frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  conf:
    userenv: ${opt:userenv, 'unknown'}
    profile: ${opt:profile,'unknown'}
    variant: ${opt:variant,'stable'}
    deploymentbucket: tco-s3

provider:
  name: aws
  region: eu-west-3
  deploymentBucket: ${self:custom.conf.deploymentbucket}
  stage: ${self:custom.conf.variant}
  stackTags:
    'testtag:user': tco

functions:
  LambdaTest1:
    name: lambda-${self:custom.conf.variant}-helloW-1
    handler: lambda-test-1/helloworld.handler
    runtime: python3.6

  LambdaTest2:
    name: lambda-${self:custom.conf.variant}-helloW-2
    handler: lambda-test-2/helloworld.handler
    runtime: python3.6