service: stack-${self:custom.conf.userenv}-${self:custom.conf.name}
frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  conf:
    userenv: ${opt:userenv, 'unknown'}
    deploymentbucket: tco-s3
    name: ${opt:name,'noname'}

provider:
  name: aws
  region: eu-west-3
  deploymentBucket: ${self:custom.conf.deploymentbucket}
  stackTags:
    'testtag:user': tco

functions:
  - ${file(./functions/services.yml)}