LambdaTest1:
  name: lambda-${self:custom.conf.userenv}-helloW-1
  handler: lambda-test1/helloworld.handler
  runtime: python3.6

LambdaTest2:
  name: lambda-${self:custom.conf.userenv}-helloW-2
  handler: lambda-test2/helloworld.handler
  runtime: python3.6